truncate table closing_stocks;
truncate table consumption_records;
truncate table public.fsn_classifications;
truncate table public.hospital_settings;
truncate table public.hospitals cascade;
truncate table public.indent_reports;
truncate table public.item_categories cascade;
truncate table public.item_category_settings;
truncate table public.item_group_settings;
truncate table public.item_groups cascade;
truncate table public.item_settings;
truncate table public.item_suppliers;
truncate table public.items cascade;
truncate table public.open_indents;
truncate table public.store_settings;
truncate table public.stores cascade;
truncate table public.supplier_settings;
truncate table public.suppliers cascade;
truncate table public.surge_records;
truncate table public.ved_classifications;
